# Generated by Django 4.1.1 on 2022-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_post_tags_alter_comment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=50),
        ),
    ]
